name:  iFT3700-HW2
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - pandas
  - scipy
  - jupyterlab
  - matplotlib
  - seaborn
  - youtube-dl
  - tqdm
  - ffmpeg-python
  - pysoundfile
  - librosa